Add support for Azure Blob Storage

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -59,20 +59,14 @@ jobs:
         matrix:
           python-version: [3.6, 3.7]
           it-backend: [local, s3, gcs]
+          # IBM not included by default due to lite plan quota being easily exceeded
+          # it-backend: [local, s3, gcs, ibm]
           cassandra-version: [2.2.14, 3.11.7, 'github:apache/trunk']
           experimental: [false]
-          exclude:
-            - cassandra-version: 'github:apache/trunk'
-              it-backend: local
           include:
             - python-version: 3.7
               tox-py: py37
             - python-version: 3.6
-              tox-py: py36
-            - cassandra-version: 'github:apache/trunk'
-              experimental: true
-              python-version: 3.6
-              it-backend: local
               tox-py: py36
     runs-on: ubuntu-18.04
     steps:
@@ -105,11 +99,19 @@ jobs:
         AWS_SECRET_ACCESS_KEY: ${{ secrets.BUCKET_SECRET }}
       run: |
         set -e
-        if [[ ( -n "${AWS_ACCESS_KEY_ID}" && "${{ matrix.it-backend }}" == "s3" ) || ( "${{ matrix.it-backend }}" == "local" ) || ( -n '${{ secrets.MEDUSA_GCS_CREDENTIALS }}' && "${{ matrix.it-backend }}" == "gcs" ) ]];
+        if [[ ( -n "${AWS_ACCESS_KEY_ID}" && "${{ matrix.it-backend }}" == "s3" ) || ( "${{ matrix.it-backend }}" == "local" ) || ( -n '${{ secrets.MEDUSA_GCS_CREDENTIALS }}' && "${{ matrix.it-backend }}" == "gcs" ) || ( -n '${{ secrets.MEDUSA_IBM_CREDENTIALS }}' && "${{ matrix.it-backend }}" == "ibm" ) ]];
         then
           . venv/bin/activate
+          if [[ "${{ matrix.it-backend }}" == "ibm" ]];
+          then
+            # Prevent awscli from using AWS secrets in case we're running against IBM cloud
+            unset AWS_ACCESS_KEY_ID
+            unset AWS_SECRET_ACCESS_KEY
+          fi
           # Write GCS service account credentials to a file
           echo '${{ secrets.MEDUSA_GCS_CREDENTIALS }}' > ~/medusa_credentials.json
+          mkdir ~/.aws
+          printf "%s" '${{ secrets.MEDUSA_IBM_CREDENTIALS }}' > ~/.aws/ibm_credentials
           # This fake cluster needs to be created first so that the integration tests pass in GH actions. Don't ask me why...
           ccm create test_cluster -v binary:3.11.4 -n 1 --vnodes
           ccm node1 updateconf 'storage_port: 7011'
@@ -128,6 +130,9 @@ jobs:
           elif [ "${{ matrix.it-backend }}" == "gcs" ]
           then
             ./run_integration_tests.sh -v --gcs --no-local --cassandra-version=${{ matrix.cassandra-version }}
+          elif [ "${{ matrix.it-backend }}" == "ibm" ]
+          then
+            ./run_integration_tests.sh -v --ibm --no-local --cassandra-version=${{ matrix.cassandra-version }}
           else
             ./run_integration_tests.sh -v --cassandra-version=${{ matrix.cassandra-version }}
           fi
@@ -140,6 +145,35 @@ jobs:
     runs-on: ubuntu-18.04
     steps:
     - uses: actions/checkout@v1
+    - name: Build and publish Debian
+      env:
+        BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
+        BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
+        SUITES: "bionic xenial buster stretch"
+      run: |
+        cd packaging/docker-build
+        $all_suites=($SUITES) # dash supports arrays expansion
+        for suite in $all_suites
+        do
+          docker-compose build "cassandra-medusa-builder-${suite} \
+            && docker-compose run "cassandra-medusa-builder-${suite}"
+        done
+        cd ../..
+        version=$(cat VERSION)
+        for suite in $all_suites
+        do
+          if [ -f "packages/cassandra-medusa_${version}-0~${suite}0_amd64.deb" ]; then
+            echo "uploading packages/cassandra-medusa_${version}-0~${suite}0_amd64.deb from ${suite} to Bintray"
+            curl -T "packages/cassandra-medusa_${version}-0~${suite}0_amd64.deb" \
+              -u${BINTRAY_USERNAME}:${BINTRAY_KEY} \
+              -H X-Bintray-Debian-Distribution:${suite} -H X-Bintray-Debian-Component:main -H X-Bintray-Debian-Architecture:amd64 -H X-Bintray-Version:${version} \
+              https://api.bintray.com/content/thelastpickle/medusa-deb/cassandra-medusa/${version}/cassandra-medusa_${version}-0~${suite}0_amd64.deb
+          else
+            echo "Error: no packages found for ${suite}"
+          fi
+        done
+        echo "Publishing release in Bintray"
+        curl -X POST -u${BINTRAY_USERNAME}:${BINTRAY_KEY} https://api.bintray.com/content/thelastpickle/medusa-deb/cassandra-medusa/${version}/publish
     - name: Set up Python 3.6
       uses: actions/setup-python@v1
       with:
@@ -161,20 +195,3 @@ jobs:
         pip install setuptools wheel twine
         python setup.py sdist bdist_wheel
         twine upload dist/*
-    - name: Build and publish Debian
-      env:
-        BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
-        BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
-      run: |
-        cd packaging/docker-build
-        docker-compose build cassandra-medusa-builder && docker-compose run cassandra-medusa-builder
-        cd ../..
-        debPackage=$(ls packages/*.deb)
-        version=$(cat VERSION)
-        echo "uploading ${debPackage} to Bintray"
-        curl -T packages/cassandra-medusa_${version}_amd64.deb \
-          -u${BINTRAY_USERNAME}:${BINTRAY_KEY} \
-          -H X-Bintray-Debian-Distribution:wheezy,bionic,jessie,xenial -H X-Bintray-Debian-Component:main -H X-Bintray-Debian-Architecture:amd64 -H X-Bintray-Version:${version} \
-          https://api.bintray.com/content/thelastpickle/medusa-deb/cassandra-medusa/${version}/cassandra-medusa_${version}_amd64.deb
-        echo "Publishing release in Bintray"
-        curl -X POST -u${BINTRAY_USERNAME}:${BINTRAY_KEY} https://api.bintray.com/content/thelastpickle/medusa-deb/cassandra-medusa/${version}/publish
